### PR TITLE
perldoc tweaks, point bugtracker at correct place, test coverage increase, is_role method

### PR DESCRIPTION
**Pull request by leejo**
is_role method/condition added to be more consistent since has_priv maps to has_priv it seems that is_role should also map to is_role (as well as is)

### CODE REVIEW

**Comment by leejo** [comment]
Buuuuuuump!

**Comment by leejo** [comment]
Bump bump bump... want me to take over maintenance of this module?

**Comment by byterock** [comment]
Funny never seen this before though it was spam.  Will fix this up

**Comment by byterock** [comment]
Ok the code looks ok  will release it to Cpan  soon

**Comment by leejo** [comment]
Thanks!

**Comment by leejo** [comment]
Hold back on the release to CPAN, i've got another PR that i want to raise.

**Comment by byterock** [comment]
ok nice one glad to see some one likes it.

will release if you are done

**Comment by leejo** [comment]
Yep, done and done. Thanks!

**Pull request merged**
